# Generated by Django 5.0.2 on 2024-02-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_id', models.CharField(max_length=12)),
                ('timestamp', models.DateTimeField()),
                ('rpg_status', models.IntegerField(choices=[(1, 'Booking'), (2, 'Cancellation')])),
                ('room_id', models.CharField(max_length=12)),
                ('night_of_stay', models.DateField()),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
